spring:
    # ?????? ?? ??
    datasource:
        url: jdbc:mysql://localhost:3306/novelog_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234

    # JPA ? Hibernate ??
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate # ?? ??? ???? ????? validate? ??
        properties:
          hibernate:
              format_sql: true

    #?? OAuth2 ????? ??
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
#                            - email
#                            - profile