spring:
    datasource:
        url: jdbc:mysql://localhost:3306/novelog_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
              format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - email
                            - profile

# Google Books API 설정
google:
  books:
    api:
      url: 'https://www.googleapis.com/books/v1/volumes'
      key: ${GOOGLE_BOOKS_API_KEY}

# Gemini API 설정 추가
gemini:
  api:
    url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent'
    key: ${GEMINI_API_KEY}